# Generated by Django 4.1.2 on 2022-11-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_Risk', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WeightCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BmiChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.CharField(max_length=10)),
                ('health_Risk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmi.health')),
                ('weight_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmi.weightcat')),
            ],
        ),
    ]
