# Generated by Django 4.1.2 on 2022-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
